#
# CircleCI 2.0 Gatsby to Firebase Configuration File
#

version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.13.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}

          paths:
            - ./node_modules

      - run:
          name: Gatsby Build
          command: ./node_modules/.bin/gatsby build # --prefix-paths enable this when deploying to a subfolder needed

      - run:
          name: Deploy to server by FTP
          command: node .circleci/deploy.js

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master # only deploy the master branch
